[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino
monitor_speed = 115200

board_build.flash_mode = dio
board_build.partitions = default

build_flags =
  -D CAMERA_MODEL_AI_THINKER

lib_deps =
  esp32-camera
  WiFi
  WebServer
